// Code generated by openapi-client-generator. DO NOT EDIT.

package client

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"time"
)

// pathReplace substitutes a {param} placeholder in a URL path, encoding the value
// with its RFC 6570 path style (simple/label/matrix) and percent-escaping each
// component so reserved characters stay within one segment.
func pathReplace(path, param, style string, explode bool, value any) string {
	v := ""
	if rv, ok := derefParam(value); ok {
		v = encodePath(param, style, explode, rv)
	}
	return strings.Replace(path, "{"+param+"}", v, 1)
}

// derefParam unwraps one pointer level, returning ok=false for a nil interface
// or nil pointer (a value to skip).
func derefParam(value any) (reflect.Value, bool) {
	if value == nil {
		return reflect.Value{}, false
	}
	rv := reflect.ValueOf(value)
	if rv.Kind() == reflect.Pointer {
		if rv.IsNil() {
			return reflect.Value{}, false
		}
		rv = rv.Elem()
	}
	// A union is a wrapper around the value it decoded, and the server is owed
	// the value, not the wrapper.
	if u, ok := rv.Interface().(unionValuer); ok {
		return derefParam(u.unionValue())
	}
	return rv, true
}

// unionValuer is implemented by every generated union.
type unionValuer interface {
	unionValue() any
}

// isSlice reports whether rv is a multi-value slice; a []byte is a scalar
// (formatScalar renders it as base64), not a list of bytes.
func isSlice(rv reflect.Value) bool {
	return rv.Kind() == reflect.Slice && !isByteSlice(rv)
}

// isByteSlice reports whether rv is a []byte, the Go type of an OpenAPI
// format: byte or format: binary value.
func isByteSlice(rv reflect.Value) bool {
	return rv.Kind() == reflect.Slice && rv.Type().Elem().Kind() == reflect.Uint8
}

// isObject reports whether rv is a struct or map to serialize property-by-property;
// a time.Time is a scalar, not an object.
func isObject(rv reflect.Value) bool {
	switch rv.Kind() {
	case reflect.Map:
		return true
	case reflect.Struct:
		_, isTime := rv.Interface().(time.Time)
		return !isTime
	}
	return false
}

// formatScalar renders a single value: time.Time as RFC 3339, a byte slice
// (OpenAPI format:byte) as base64, floats as plain decimals (never scientific
// notation), everything else with default formatting. Kind is checked rather than
// the concrete type so a defined type (e.g. `type Weight float64` from a number
// enum) is still formatted correctly.
func formatScalar(rv reflect.Value) string {
	if t, ok := rv.Interface().(time.Time); ok {
		return t.Format(time.RFC3339)
	}
	switch rv.Kind() {
	case reflect.Slice:
		if isByteSlice(rv) {
			return base64.StdEncoding.EncodeToString(rv.Bytes())
		}
	case reflect.Float32:
		return strconv.FormatFloat(rv.Float(), 'f', -1, 32)
	case reflect.Float64:
		return strconv.FormatFloat(rv.Float(), 'f', -1, 64)
	}
	return fmt.Sprintf("%v", rv.Interface())
}

// formatValue renders a value that may be a scalar or a flattened collection: a
// slice becomes a comma list, an object a comma list of its property values,
// everything else a scalar. An interface element (from a []any) is unwrapped first.
func formatValue(rv reflect.Value) string {
	if rv.Kind() == reflect.Interface {
		if rv.IsNil() {
			return ""
		}
		rv = rv.Elem()
	}
	switch {
	case isSlice(rv):
		return strings.Join(sliceValues(rv), ",")
	case isObject(rv):
		flat := make([]string, 0)
		for _, p := range objectPairs(rv) {
			flat = append(flat, p[0], p[1])
		}
		return strings.Join(flat, ",")
	default:
		return formatScalar(rv)
	}
}

// sliceValues renders each element of a slice, flattening nested collections.
func sliceValues(rv reflect.Value) []string {
	out := make([]string, rv.Len())
	for i := range out {
		out[i] = formatValue(rv.Index(i))
	}
	return out
}

// namedValue is one property of an object: its wire name and its value, with any
// pointer already unwrapped.
type namedValue struct {
	name  string
	value reflect.Value
}

// objectValues returns an object's properties in a stable order: struct fields in
// declaration order keyed by their json tag (an embedded field's properties are
// flattened in), map keys sorted. A nil pointer property is skipped.
func objectValues(rv reflect.Value) []namedValue {
	var values []namedValue
	switch rv.Kind() {
	case reflect.Struct:
		t := rv.Type()
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			if f.PkgPath != "" {
				continue
			}
			fv, ok := derefParam(rv.Field(i).Interface())
			if !ok {
				continue
			}
			// An embedded struct and the additionalProperties catch-all both hold
			// properties of this object, not properties of their own.
			if (f.Anonymous || f.Tag.Get("openapi") == "additionalProperties") && isObject(fv) {
				values = append(values, objectValues(fv)...)
				continue
			}
			name, _, _ := strings.Cut(f.Tag.Get("json"), ",")
			if name == "" {
				name = f.Name
			}
			if name == "-" {
				continue
			}
			values = append(values, namedValue{name, fv})
		}
	case reflect.Map:
		keys := make([]string, 0, rv.Len())
		byKey := make(map[string]reflect.Value, rv.Len())
		for _, k := range rv.MapKeys() {
			s := fmt.Sprintf("%v", k.Interface())
			keys = append(keys, s)
			byKey[s] = rv.MapIndex(k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			if fv, ok := derefParam(byKey[k].Interface()); ok {
				values = append(values, namedValue{k, fv})
			}
		}
	}
	return values
}

// objectPairs renders an object's properties as flat (property, value) pairs.
func objectPairs(rv reflect.Value) [][2]string {
	values := objectValues(rv)
	if len(values) == 0 {
		return nil
	}
	pairs := make([][2]string, 0, len(values))
	for _, v := range values {
		pairs = append(pairs, [2]string{v.name, formatValue(v.value)})
	}
	return pairs
}

// addQueryParam encodes one query parameter under its OpenAPI style/explode. A nil
// optional pointer is skipped, but a present zero value (0/false/"") is sent — the
// pointer already signals "unset".
func addQueryParam(values url.Values, key, style string, explode bool, value any) {
	rv, ok := derefParam(value)
	if !ok {
		return
	}
	switch {
	case isObject(rv):
		pairs := objectPairs(rv)
		if len(pairs) == 0 {
			return
		}
		switch {
		case style == "deepObject":
			for _, p := range pairs {
				values.Set(key+"["+p[0]+"]", p[1])
			}
		case explode:
			for _, p := range pairs {
				values.Set(p[0], p[1])
			}
		default:
			flat := make([]string, 0, len(pairs)*2)
			for _, p := range pairs {
				flat = append(flat, p[0], p[1])
			}
			values.Set(key, strings.Join(flat, ","))
		}
	case isSlice(rv):
		elems := sliceValues(rv)
		if len(elems) == 0 {
			return
		}
		if explode {
			for _, e := range elems {
				values.Add(key, e)
			}
			return
		}
		values.Set(key, strings.Join(elems, queryDelim(style)))
	default:
		values.Set(key, formatScalar(rv))
	}
}

// encodeQuery renders the query string. url.Values.Encode escapes a space as '+'
// (form encoding), but spaceDelimited params — and any value with a space — need
// the RFC 3986 '%20', so rewrite '+' to it. This is safe because Encode emits a
// literal '+' only for a space; a '+' in the data is already escaped as '%2B'.
func encodeQuery(values url.Values) string {
	return strings.ReplaceAll(values.Encode(), "+", "%20")
}

// reservedPassthrough are the RFC 3986 reserved characters a parameter marked
// allowReserved sends unescaped. The separators a query string is itself parsed
// with are missing on purpose: passing "&", "=", or "#" through would end the
// value early, and "+" reads as a space, so a value carrying any of them would
// arrive as something other than what was sent.
const reservedPassthrough = `:/?[]@!$'()*,;`

// encodeQueryAllowingReserved renders the query with the named keys' values left
// unescaped over the reserved set. Every other key is encoded as usual.
func encodeQueryAllowingReserved(values url.Values, reservedKeys ...string) string {
	reserved := make(map[string]bool, len(reservedKeys))
	for _, k := range reservedKeys {
		reserved[k] = true
	}

	keys := make([]string, 0, len(values))
	for k := range values {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	for _, k := range keys {
		for _, v := range values[k] {
			if b.Len() > 0 {
				b.WriteByte('&')
			}
			b.WriteString(url.QueryEscape(k))
			b.WriteByte('=')
			if reserved[k] {
				b.WriteString(escapeAllowingReserved(v))
			} else {
				b.WriteString(strings.ReplaceAll(url.QueryEscape(v), "+", "%20"))
			}
		}
	}
	return b.String()
}

// escapeAllowingReserved percent-encodes a value except for the reserved
// characters the spec says to pass through.
func escapeAllowingReserved(value string) string {
	var b strings.Builder
	for i := 0; i < len(value); i++ {
		if c := value[i]; strings.IndexByte(reservedPassthrough, c) >= 0 {
			b.WriteByte(c)
			continue
		}
		b.WriteString(strings.ReplaceAll(url.QueryEscape(string(value[i])), "+", "%20"))
	}
	return b.String()
}

// queryDelim is the separator for an unexploded array under a query style.
func queryDelim(style string) string {
	switch style {
	case "spaceDelimited":
		return " "
	case "pipeDelimited":
		return "|"
	default:
		return ","
	}
}

// encodeSimple renders a value in the simple style (header params): a scalar
// as-is, an array comma-joined, an object as a flat comma list of property/value,
// or "prop=value" pairs when exploded.
func encodeSimple(rv reflect.Value, explode bool) string {
	switch {
	case isObject(rv):
		pairs := objectPairs(rv)
		parts := make([]string, 0, len(pairs))
		for _, p := range pairs {
			if explode {
				parts = append(parts, p[0]+"="+p[1])
			} else {
				parts = append(parts, p[0], p[1])
			}
		}
		return strings.Join(parts, ",")
	case isSlice(rv):
		return strings.Join(sliceValues(rv), ",")
	default:
		return formatScalar(rv)
	}
}

// pathEscape percent-encodes a path component, additionally escaping '=' so a
// value can't be mistaken for a matrix/label key=value separator.
func pathEscape(s string) string {
	return strings.ReplaceAll(url.PathEscape(s), "=", "%3D")
}

// encodePath renders a path parameter per RFC 6570 (simple/label/matrix),
// percent-escaping each component so reserved characters stay in one segment.
func encodePath(name, style string, explode bool, rv reflect.Value) string {
	var items [][2]string // (key, value); key empty for scalars and array elements
	switch {
	case isObject(rv):
		for _, p := range objectPairs(rv) {
			items = append(items, [2]string{pathEscape(p[0]), pathEscape(p[1])})
		}
	case isSlice(rv):
		for _, v := range sliceValues(rv) {
			items = append(items, [2]string{"", pathEscape(v)})
		}
	default:
		items = append(items, [2]string{"", pathEscape(formatScalar(rv))})
	}
	// An empty list/object expands to nothing (RFC 6570 §2.3), so no prefix.
	if len(items) == 0 {
		return ""
	}

	switch style {
	case "label":
		return "." + strings.Join(pathTokens(items, explode), pathSep(explode, "."))
	case "matrix":
		if explode {
			var b strings.Builder
			for _, t := range items {
				b.WriteString(";")
				if t[0] != "" {
					b.WriteString(t[0] + "=" + t[1])
				} else {
					b.WriteString(name + "=" + t[1])
				}
			}
			return b.String()
		}
		return ";" + name + "=" + strings.Join(pathTokens(items, false), ",")
	default: // simple
		return strings.Join(pathTokens(items, explode), pathSep(explode, ","))
	}
}

// pathTokens flattens (key,value) items: bare values for arrays/scalars, "key=value"
// when an object is exploded, else "key,value" pairs.
func pathTokens(items [][2]string, explode bool) []string {
	var out []string
	for _, t := range items {
		switch {
		case t[0] == "":
			out = append(out, t[1])
		case explode:
			out = append(out, t[0]+"="+t[1])
		default:
			out = append(out, t[0], t[1])
		}
	}
	return out
}

// pathSep is the separator between exploded items for a style (label uses ".",
// simple ",").
func pathSep(explode bool, exploded string) string {
	if explode {
		return exploded
	}
	return ","
}

// hasRequestBody reports whether there is a body to send. An optional body
// arrives as a nil pointer inside an interface, which is not itself nil, and
// encoding it would send the JSON literal null where the caller meant to send
// nothing at all.
func hasRequestBody(body any) bool {
	if body == nil {
		return false
	}
	rv := reflect.ValueOf(body)
	return rv.Kind() != reflect.Pointer || !rv.IsNil()
}

// isRawResult fills a result the operation types as bytes or text with the body
// as it arrived, reporting whether it did. Such a body is the value itself, not
// a document to parse.
func isRawResult(result any, body []byte) bool {
	switch v := result.(type) {
	case *[]byte:
		*v = body
		return true
	case *string:
		*v = string(body)
		return true
	}
	return false
}

// contentParamValue serializes a parameter declared with a media type rather than
// a style. A nil optional pointer yields no value at all, which the callers skip.
func contentParamValue(value any) (string, bool) {
	rv, ok := derefParam(value)
	if !ok {
		return "", false
	}
	encoded, err := json.Marshal(rv.Interface())
	if err != nil {
		return "", false
	}
	return string(encoded), true
}

// addContentQueryParam adds a query parameter whose value is a serialized
// document. The document goes in whole, percent-encoded by the query encoder.
func addContentQueryParam(values url.Values, key string, value any) {
	if encoded, ok := contentParamValue(value); ok {
		values.Set(key, encoded)
	}
}

// setContentHeader sets a header whose value is a serialized document.
func setContentHeader(headers http.Header, name string, value any) {
	if encoded, ok := contentParamValue(value); ok {
		headers.Set(name, encoded)
	}
}

// addContentCookieHeader appends a cookie whose value is a serialized document.
func addContentCookieHeader(headers http.Header, name string, value any) {
	if encoded, ok := contentParamValue(value); ok {
		cookie := (&http.Cookie{Name: name, Value: encoded}).String()
		if existing := headers.Get("Cookie"); existing != "" {
			headers.Set("Cookie", existing+"; "+cookie)
		} else {
			headers.Set("Cookie", cookie)
		}
	}
}

// setHeader sets a header parameter (simple style), skipping a nil optional
// pointer.
func setHeader(headers http.Header, name string, explode bool, value any) {
	rv, ok := derefParam(value)
	if !ok {
		return
	}
	headers.Set(name, encodeSimple(rv, explode))
}

// encodeRequestBody renders a request body under the media type its operation
// declares, returning the payload and the Content-Type to send it with.
func encodeRequestBody(body any, contentType string) ([]byte, string, error) {
	if contentType == "" {
		contentType = "application/json"
	}
	data, err := json.Marshal(body)
	if err != nil {
		return nil, "", fmt.Errorf("encoding request body: %w", err)
	}
	return data, contentType, nil
}

// addCookieHeader appends a cookie to the Cookie header, skipping nil optional
// values. A Cookie header is a single name=value, so arrays and objects are
// flattened (form style, unexploded); http.Cookie sanitizes invalid octets.
func addCookieHeader(headers http.Header, name string, value any) {
	rv, ok := derefParam(value)
	if !ok {
		return
	}
	cookie := (&http.Cookie{Name: name, Value: encodeSimple(rv, false)}).String()
	if existing := headers.Get("Cookie"); existing != "" {
		headers.Set("Cookie", existing+"; "+cookie)
	} else {
		headers.Set("Cookie", cookie)
	}
}
