// Code generated by openapi-client-generator. DO NOT EDIT.

package client

import (
	"context"
)

// GetRoot - Health check
//
// Returns a simple greeting to confirm the server is running. No authentication is required.
func (c *Client) GetRoot(ctx context.Context) (*string, error) {

	path := "/"

	var result string
	if err := c.do(ctx, "GET", path, nil, "", &result, "text/plain", true); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetApp - Get an app
//
// Retrieves the details of an app by its ID. Requires an authenticated user.
func (c *Client) GetApp(ctx context.Context, app string) (*AppResponse, error) {

	path := "/app/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	var result AppResponse
	if err := c.do(ctx, "GET", path, nil, "", &result, "application/json", true); err != nil {
		return nil, parseErrorResponseResponse(err)
	}
	return &result, nil
}

// ModifyApp - Modify an app
//
// Updates the name, description, or limits of an existing app. Requires an authenticated admin user.
func (c *Client) ModifyApp(ctx context.Context, app string, body AppRequest) (*AppResponse, error) {

	path := "/app/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	var result AppResponse
	if err := c.do(ctx, "PUT", path, body, "application/json", &result, "application/json", true); err != nil {
		return nil, parseErrorResponseResponse(err)
	}
	return &result, nil
}

// DeleteApp - Delete an app
//
// Permanently deletes an app by its ID. Requires an authenticated admin user.
func (c *Client) DeleteApp(ctx context.Context, app string) (*SuccessResponse, error) {

	path := "/app/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	var result SuccessResponse
	if err := c.do(ctx, "DELETE", path, nil, "", &result, "application/json", true); err != nil {
		return nil, parseErrorResponseResponse(err)
	}
	return &result, nil
}

// CreateApp - Create an app
//
// Creates a new app owned by the authenticated user. Requires an authenticated admin user.
func (c *Client) CreateApp(ctx context.Context, body AppRequest) (*AppResponse, error) {

	path := "/app"

	var result AppResponse
	if err := c.do(ctx, "POST", path, body, "application/json", &result, "application/json", true); err != nil {
		return nil, parseErrorResponseResponse(err)
	}
	return &result, nil
}

// GetUser - Get current user
//
// Retrieves the profile and authorised apps of the authenticated user. Requires an authenticated user.
func (c *Client) GetUser(ctx context.Context) (*UserResponse, error) {

	path := "/user"

	var result UserResponse
	if err := c.do(ctx, "GET", path, nil, "", &result, "application/json", true); err != nil {
		return nil, parseErrorResponseResponse(err)
	}
	return &result, nil
}

// DeleteUser - Delete current user
//
// Permanently deletes the authenticated user's account. Requires an authenticated user.
func (c *Client) DeleteUser(ctx context.Context) (*SuccessResponse, error) {

	path := "/user"

	var result SuccessResponse
	if err := c.do(ctx, "DELETE", path, nil, "", &result, "application/json", true); err != nil {
		return nil, parseErrorResponseResponse(err)
	}
	return &result, nil
}

// AuthoriseUser - Authorise user to an app
//
// Grants the authenticated user access to the specified app. Requires an authenticated user.
func (c *Client) AuthoriseUser(ctx context.Context, app string) (*UserResponse, error) {

	path := "/user/to/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	var result UserResponse
	if err := c.do(ctx, "PUT", path, nil, "", &result, "application/json", true); err != nil {
		return nil, parseErrorResponseResponse(err)
	}
	return &result, nil
}

// DeauthoriseUser - Deauthorise user from an app
//
// Revokes the authenticated user's access to the specified app. Requires an authenticated user.
func (c *Client) DeauthoriseUser(ctx context.Context, app string) (*UserResponse, error) {

	path := "/user/from/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	var result UserResponse
	if err := c.do(ctx, "DELETE", path, nil, "", &result, "application/json", true); err != nil {
		return nil, parseErrorResponseResponse(err)
	}
	return &result, nil
}

// GetPref - Get a preference
//
// Retrieves the authenticated user's stored preference payload for the given app. Requires an authenticated user.
func (c *Client) GetPref(ctx context.Context, app string) (*PrefResponse, error) {

	path := "/pref/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	var result PrefResponse
	if err := c.do(ctx, "GET", path, nil, "", &result, "application/json", true); err != nil {
		return nil, parseErrorResponseResponse(err)
	}
	return &result, nil
}

// PostPref - Update a preference
//
// Creates or updates the authenticated user's preference payload for the given app, subject to the app's payload size limit. Requires an authenticated user.
func (c *Client) PostPref(ctx context.Context, app string, body map[string]any) (*PrefResponse, error) {

	path := "/pref/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	var result PrefResponse
	if err := c.do(ctx, "POST", path, body, "application/json", &result, "application/json", true); err != nil {
		return nil, parseErrorResponseResponse(err)
	}
	return &result, nil
}

// DeletePref - Delete a preference
//
// Deletes the authenticated user's stored preference for the given app. Requires an authenticated user.
func (c *Client) DeletePref(ctx context.Context, app string) (*SuccessResponse, error) {

	path := "/pref/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	var result SuccessResponse
	if err := c.do(ctx, "DELETE", path, nil, "", &result, "application/json", true); err != nil {
		return nil, parseErrorResponseResponse(err)
	}
	return &result, nil
}

// PostPrefFromSource - Update a preference from a source
//
// Creates or updates the authenticated user's preference for the given app, tagging the update with a source identifier so it can be excluded from that source's own notification stream. Requires an authenticated user.
func (c *Client) PostPrefFromSource(ctx context.Context, app string, src string, body map[string]any) (*PrefResponse, error) {

	path := "/pref/{app}/from/{src}"
	path = pathReplace(path, "app", "simple", false, app)
	path = pathReplace(path, "src", "simple", false, src)

	var result PrefResponse
	if err := c.do(ctx, "POST", path, body, "application/json", &result, "application/json", true); err != nil {
		return nil, parseErrorResponseResponse(err)
	}
	return &result, nil
}

// StartNotification - Stream preference notifications
//
// Opens a server-sent events stream that emits notifications whenever the authenticated user's preference for the given app changes. Requires an authenticated user.
func (c *Client) StartNotification(ctx context.Context, app string) (*Notification, error) {

	path := "/pref/notification/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	var result Notification
	if err := c.do(ctx, "GET", path, nil, "", &result, "text/event-stream", true); err != nil {
		return nil, parseErrorResponseResponse(err)
	}
	return &result, nil
}

// StartNotificationStream is StartNotification with the response taken as it arrives, one
// server-sent event at a time. Close the stream when finished with it.
func (c *Client) StartNotificationStream(ctx context.Context, app string) (*EventStream[Notification], error) {

	path := "/pref/notification/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	resp, err := c.doStream(ctx, "GET", path, nil, "", "text/event-stream", true)
	if err != nil {
		return nil, parseErrorResponseResponse(err)
	}
	return newEventStream[Notification](resp), nil
}

// StartNotificationFromSource - Stream preference notifications excluding a source
//
// Opens a server-sent events stream of preference change notifications for the given app, excluding updates originating from the given source. Requires an authenticated user.
func (c *Client) StartNotificationFromSource(ctx context.Context, app string, src string) (*Notification, error) {

	path := "/pref/notification/{app}/from/{src}"
	path = pathReplace(path, "app", "simple", false, app)
	path = pathReplace(path, "src", "simple", false, src)

	var result Notification
	if err := c.do(ctx, "GET", path, nil, "", &result, "text/event-stream", true); err != nil {
		return nil, parseErrorResponseResponse(err)
	}
	return &result, nil
}

// StartNotificationFromSourceStream is StartNotificationFromSource with the response taken as it arrives, one
// server-sent event at a time. Close the stream when finished with it.
func (c *Client) StartNotificationFromSourceStream(ctx context.Context, app string, src string) (*EventStream[Notification], error) {

	path := "/pref/notification/{app}/from/{src}"
	path = pathReplace(path, "app", "simple", false, app)
	path = pathReplace(path, "src", "simple", false, src)

	resp, err := c.doStream(ctx, "GET", path, nil, "", "text/event-stream", true)
	if err != nil {
		return nil, parseErrorResponseResponse(err)
	}
	return newEventStream[Notification](resp), nil
}
