// Code generated by openapi-client-generator. DO NOT EDIT.

package client

import (
	"context"
	"net/url"
)

// GetRoot - Health check / root endpoint.
func (c *Client) GetRoot(ctx context.Context) (*string, error) {

	path := "/"

	var result string
	if err := c.do(ctx, "GET", path, nil, "", &result, "text/plain", false); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetAuthCallbackParams contains the parameters for the GetAuthCallback operation.
// Required parameters are value fields; optional parameters are pointers.
type GetAuthCallbackParams struct {
	// Authorization code issued by the embedded IDP.
	Code string `json:"code"`
}

// GetAuthCallback - OAuth2 authorization code callback for the embedded local IDP.
//
// Only mounted when `IDP.Enable` is true in configuration (`server/server.go`, `server/idp.go`). Exchanges the `code` query parameter for a token against the embedded IDP's token endpoint and returns the raw `golang.org/x/oauth2.Token` response. Intended for local development/testing only.
func (c *Client) GetAuthCallback(ctx context.Context, params GetAuthCallbackParams) (*OAuthToken, error) {

	path := "/auth-cb"
	queryValues := url.Values{}
	addQueryParam(queryValues, "code", "form", true, params.Code)

	if len(queryValues) > 0 {
		path += "?" + encodeQuery(queryValues)
	}

	var result OAuthToken
	if err := c.do(ctx, "GET", path, nil, "", &result, "application/json", false); err != nil {
		return nil, parseErrorResponse(err)
	}
	return &result, nil
}

// GetApp - Get an app by ID.
func (c *Client) GetApp(ctx context.Context, app string) (*App, error) {

	path := "/app/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	var result App
	if err := c.do(ctx, "GET", path, nil, "", &result, "application/json", true); err != nil {
		return nil, parseErrorResponse(err)
	}
	return &result, nil
}

// ModifyApp - Modify an existing app.
//
// Nominally restricted to admins via the `IsAdmin` middleware (see the `IsAdmin` no-op caveat in the top-level description).
func (c *Client) ModifyApp(ctx context.Context, app string, body AppUpsertRequest) (*App, error) {

	path := "/app/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	var result App
	if err := c.do(ctx, "PUT", path, body, "application/json", &result, "application/json", true); err != nil {
		return nil, parseErrorResponse(err)
	}
	return &result, nil
}

// DeleteApp - Delete an app.
//
// Nominally restricted to admins via the `IsAdmin` middleware (see the `IsAdmin` no-op caveat in the top-level description).
func (c *Client) DeleteApp(ctx context.Context, app string) (*SuccessResponse, error) {

	path := "/app/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	var result SuccessResponse
	if err := c.do(ctx, "DELETE", path, nil, "", &result, "application/json", true); err != nil {
		return nil, parseErrorResponse(err)
	}
	return &result, nil
}

// CreateApp - Register a new app.
//
// Nominally restricted to admins via the `IsAdmin` middleware (see the `IsAdmin` no-op caveat in the top-level description). The creating user's ID is taken from the authenticated session and stored as `created_by`.
func (c *Client) CreateApp(ctx context.Context, body AppUpsertRequest) (*App, error) {

	path := "/app"

	var result App
	if err := c.do(ctx, "POST", path, body, "application/json", &result, "application/json", true); err != nil {
		return nil, parseErrorResponse(err)
	}
	return &result, nil
}

// GetUser - Get the authenticated user's own record.
func (c *Client) GetUser(ctx context.Context) (*User, error) {

	path := "/user"

	var result User
	if err := c.do(ctx, "GET", path, nil, "", &result, "application/json", true); err != nil {
		return nil, parseErrorResponse(err)
	}
	return &result, nil
}

// DeleteUser - Delete the authenticated user's own account.
func (c *Client) DeleteUser(ctx context.Context) (*SuccessResponse, error) {

	path := "/user"

	var result SuccessResponse
	if err := c.do(ctx, "DELETE", path, nil, "", &result, "application/json", true); err != nil {
		return nil, parseErrorResponse(err)
	}
	return &result, nil
}

// AuthoriseUser - Authorise the authenticated user to use an app.
func (c *Client) AuthoriseUser(ctx context.Context, app string) (*User, error) {

	path := "/user/to/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	var result User
	if err := c.do(ctx, "PUT", path, nil, "", &result, "application/json", true); err != nil {
		return nil, parseErrorResponse(err)
	}
	return &result, nil
}

// DeauthoriseUser - Deauthorise the authenticated user from an app.
func (c *Client) DeauthoriseUser(ctx context.Context, app string) (*User, error) {

	path := "/user/from/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	var result User
	if err := c.do(ctx, "DELETE", path, nil, "", &result, "application/json", true); err != nil {
		return nil, parseErrorResponse(err)
	}
	return &result, nil
}

// GetPreference - Get the authenticated user's stored preference for an app.
//
// The returned `data` field is the raw stored payload string; it is not re-parsed as JSON by the server before being embedded in the response.
func (c *Client) GetPreference(ctx context.Context, app string) (*Preference, error) {

	path := "/pref/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	var result Preference
	if err := c.do(ctx, "GET", path, nil, "", &result, "application/json", true); err != nil {
		return nil, parseErrorResponse(err)
	}
	return &result, nil
}

// PostPreference - Update the authenticated user's preference for an app.
//
// Accepts an arbitrary JSON body, which is re-encoded and stored verbatim. The response always has `data: null` regardless of the payload sent.
func (c *Client) PostPreference(ctx context.Context, app string, body map[string]any) (*Preference, error) {

	path := "/pref/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	var result Preference
	if err := c.do(ctx, "POST", path, body, "application/json", &result, "application/json", true); err != nil {
		return nil, parseErrorResponse(err)
	}
	return &result, nil
}

// DeletePreference - Delete the authenticated user's preference for an app.
func (c *Client) DeletePreference(ctx context.Context, app string) (*SuccessResponse, error) {

	path := "/pref/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	var result SuccessResponse
	if err := c.do(ctx, "DELETE", path, nil, "", &result, "application/json", true); err != nil {
		return nil, parseErrorResponse(err)
	}
	return &result, nil
}

// PostPreferenceFromSrc - Update the authenticated user's preference for an app, scoped to a source.
//
// Identical to `POST /pref/{app}`, but restricts the update to the preference entry matching the given `src` filter.
func (c *Client) PostPreferenceFromSrc(ctx context.Context, app string, src string, body map[string]any) (*Preference, error) {

	path := "/pref/{app}/from/{src}"
	path = pathReplace(path, "app", "simple", false, app)
	path = pathReplace(path, "src", "simple", false, src)

	var result Preference
	if err := c.do(ctx, "POST", path, body, "application/json", &result, "application/json", true); err != nil {
		return nil, parseErrorResponse(err)
	}
	return &result, nil
}

// StreamNotifications - Subscribe to preference-change notifications for an app via Server-Sent Events.
//
// Upgrades the connection to an SSE stream (`go.jetify.com/sse`). Emits `Fugu` events carrying the changed preference payload as `data`, and a `server-disconnected` event when the server closes the connection. The connection is held open until the client disconnects or the server shuts down; this is not a normal request/response operation, so most HTTP tooling (including Insomnia's default request execution) will show it as a long-running request rather than replaying discrete events.
func (c *Client) StreamNotifications(ctx context.Context, app string) (*string, error) {

	path := "/pref/notification/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	var result string
	if err := c.do(ctx, "GET", path, nil, "", &result, "text/event-stream", true); err != nil {
		return nil, parseErrorResponse(err)
	}
	return &result, nil
}

// StreamNotificationsStream is StreamNotifications with the response taken as it arrives, one
// server-sent event at a time. Close the stream when finished with it.
func (c *Client) StreamNotificationsStream(ctx context.Context, app string) (*EventStream[string], error) {

	path := "/pref/notification/{app}"
	path = pathReplace(path, "app", "simple", false, app)

	resp, err := c.doStream(ctx, "GET", path, nil, "", "text/event-stream", true)
	if err != nil {
		return nil, parseErrorResponse(err)
	}
	return newEventStream[string](resp), nil
}

// StreamNotificationsFromSrc - Subscribe to preference-change notifications for an app, scoped to a source, via Server-Sent Events.
//
// Identical to `GET /pref/notification/{app}`, but restricts the stream to notifications matching the given `src` filter.
func (c *Client) StreamNotificationsFromSrc(ctx context.Context, app string, src string) (*string, error) {

	path := "/pref/notification/{app}/from/{src}"
	path = pathReplace(path, "app", "simple", false, app)
	path = pathReplace(path, "src", "simple", false, src)

	var result string
	if err := c.do(ctx, "GET", path, nil, "", &result, "text/event-stream", true); err != nil {
		return nil, parseErrorResponse(err)
	}
	return &result, nil
}

// StreamNotificationsFromSrcStream is StreamNotificationsFromSrc with the response taken as it arrives, one
// server-sent event at a time. Close the stream when finished with it.
func (c *Client) StreamNotificationsFromSrcStream(ctx context.Context, app string, src string) (*EventStream[string], error) {

	path := "/pref/notification/{app}/from/{src}"
	path = pathReplace(path, "app", "simple", false, app)
	path = pathReplace(path, "src", "simple", false, src)

	resp, err := c.doStream(ctx, "GET", path, nil, "", "text/event-stream", true)
	if err != nil {
		return nil, parseErrorResponse(err)
	}
	return newEventStream[string](resp), nil
}
