// Code generated by openapi-client-generator. DO NOT EDIT.

package client

import (
	"context"
	"net/http"
)

// ResponseMeta carries what a response says outside its body: the status it
// arrived with and the headers it carried.
type ResponseMeta struct {
	StatusCode int
	Status     string
	Header     http.Header
}

type responseCaptureKey struct{}

// WithResponseCapture returns a context that records what the next response says
// outside its body, and the ResponseMeta it lands in. Calls made with the
// returned context each overwrite it, so give one capture to one call.
//
//	ctx, meta := WithResponseCapture(ctx)
//	pet, err := client.GetPetByID(ctx, 123)
//	fmt.Println(meta.StatusCode, meta.Header.Get("X-Request-Id"))
//
// An error response is captured too, so the status and headers are readable
// whether or not the call succeeded.
func WithResponseCapture(ctx context.Context) (context.Context, *ResponseMeta) {
	meta := &ResponseMeta{}
	return context.WithValue(ctx, responseCaptureKey{}, meta), meta
}

// captureResponse records resp on the ResponseMeta the caller attached to ctx.
func captureResponse(ctx context.Context, resp *http.Response) {
	meta, ok := ctx.Value(responseCaptureKey{}).(*ResponseMeta)
	if !ok || resp == nil {
		return
	}
	meta.StatusCode = resp.StatusCode
	meta.Status = resp.Status
	meta.Header = resp.Header.Clone()
}
