// Code generated by openapi-client-generator. DO NOT EDIT.

package client

import (
	"time"
)

type AppRequest struct {
	Name       *string `json:"name,omitempty"`
	Desc       *string `json:"desc,omitempty"`
	MaxPayload *int64  `json:"max_payload,omitempty"`
	MaxUser    *int64  `json:"max_user,omitempty"`
}

type AppResponse struct {
	ID         *string `json:"id,omitempty"`
	Name       *string `json:"name,omitempty"`
	Desc       *string `json:"desc,omitempty"`
	MaxPayload *int64  `json:"max_payload,omitempty"`
	MaxUser    *int64  `json:"max_user,omitempty"`
}

type UserResponse struct {
	ID           *string       `json:"id,omitempty"`
	AuthProvider *string       `json:"auth_provider,omitempty"`
	AuthSub      *string       `json:"auth_sub,omitempty"`
	Apps         []AppResponse `json:"apps,omitempty"`
}

type PrefResponse struct {
	UserID    *string    `json:"user_id,omitempty"`
	AppID     *string    `json:"app_id,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Arbitrary JSON preference payload.
	Data map[string]any `json:"data,omitempty"`
}

type Notification struct {
	User *string `json:"User,omitempty"`
	App  *string `json:"App,omitempty"`
	Src  *string `json:"Src,omitempty"`
}

type SuccessResponse struct {
	Success *bool `json:"success,omitempty"`
}

type ErrorResponse struct {
	Error   *bool   `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}
