package httptestclient

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"sync"
)

// StreamingRecorder is an http.ResponseWriter and http.Flusher implementation
// that streams response data concurrently via an io.Pipe.
type StreamingRecorder struct {
	mu          sync.Mutex
	HeaderMap   http.Header
	Code        int
	wroteHeader bool
	headerReady chan struct{}
	readyOnce   sync.Once
	pr          *io.PipeReader
	pw          *io.PipeWriter
	closeOnce   sync.Once
}

// NewStreamingRecorder creates and initializes a new StreamingRecorder.
func NewStreamingRecorder() *StreamingRecorder {
	pr, pw := io.Pipe()
	return &StreamingRecorder{
		HeaderMap:   make(http.Header),
		headerReady: make(chan struct{}),
		pr:          pr,
		pw:          pw,
	}
}

// Header returns the response headers.
func (r *StreamingRecorder) Header() http.Header {
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.HeaderMap == nil {
		r.HeaderMap = make(http.Header)
	}
	return r.HeaderMap
}

// WriteHeader sends an HTTP response header with the provided status code.
func (r *StreamingRecorder) WriteHeader(code int) {
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.wroteHeader {
		return
	}
	r.Code = code
	r.wroteHeader = true
	r.signalHeaderReady()
}

// Write writes the data to the connection as part of an HTTP reply.
func (r *StreamingRecorder) Write(buf []byte) (int, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	if !r.wroteHeader {
		if r.Code == 0 {
			r.Code = http.StatusOK
		}
		r.wroteHeader = true
		r.signalHeaderReady()
	}
	return r.pw.Write(buf)
}

// Flush writes an empty byte to the connection, as data is always written into the memory buffer instantly.
func (r *StreamingRecorder) Flush() {
	_, _ = r.Write([]byte{})
}

// CloseNotify returns a channel that receives at most a single value (true) when the client connection has gone away.
func (r *StreamingRecorder) CloseNotify() <-chan bool {
	return make(chan bool)
}

func (r *StreamingRecorder) signalHeaderReady() {
	r.readyOnce.Do(func() {
		close(r.headerReady)
	})
}

// HeaderReady returns a channel closed once response headers or status code have been set or when the handler returns.
func (r *StreamingRecorder) HeaderReady() <-chan struct{} {
	return r.headerReady
}

// Close closes the pipe writer, signaling EOF to readers.
func (r *StreamingRecorder) Close() error {
	r.closeOnce.Do(func() {
		r.signalHeaderReady()
		_ = r.pw.Close()
	})
	return nil
}

// CloseWithError closes the pipe writer with an error.
func (r *StreamingRecorder) CloseWithError(err error) error {
	r.closeOnce.Do(func() {
		r.signalHeaderReady()
		_ = r.pw.CloseWithError(err)
	})
	return nil
}

// Result returns the response generated by the handler.
func (r *StreamingRecorder) Result() *http.Response {
	code := r.Code
	if code == 0 {
		code = http.StatusOK
	}

	return &http.Response{
		Status:        fmt.Sprintf("%d %s", code, http.StatusText(code)),
		StatusCode:    code,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		Header:        r.HeaderMap.Clone(),
		Body:          r.pr,
		ContentLength: -1,
	}
}

type cancelReadCloser struct {
	io.ReadCloser
	cancel    context.CancelFunc
	closeOnce sync.Once
}

func (c *cancelReadCloser) Close() error {
	var err error
	c.closeOnce.Do(func() {
		if c.cancel != nil {
			c.cancel()
		}
		err = c.ReadCloser.Close()
	})
	return err
}

// NewStreamingClient creates a new http.Client that uses the provided handler to handle streaming requests concurrently.
func NewStreamingClient(handler http.Handler) *http.Client {
	return &http.Client{
		Transport: roundTripFunc(func(req *http.Request) (*http.Response, error) {
			rec := NewStreamingRecorder()

			ctx, cancel := context.WithCancel(req.Context())
			reqWithCancel := req.WithContext(ctx)

			go func() {
				defer func() {
					if r := recover(); r != nil {
						_ = rec.CloseWithError(fmt.Errorf("panic in handler: %v", r))
					} else {
						_ = rec.Close()
					}
				}()
				handler.ServeHTTP(rec, reqWithCancel)
			}()

			// Wait until the handler has written the header or the request context is canceled.
			select {
			case <-req.Context().Done():
				cancel()
				return nil, req.Context().Err()
			case <-rec.HeaderReady():
			}

			// Return the response with headers and streaming body.
			resp := rec.Result()
			resp.Request = req
			resp.Body = &cancelReadCloser{
				ReadCloser: resp.Body,
				cancel:     cancel,
			}

			return resp, nil
		}),
	}
}
