name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -v -o pref-syncs .

      - name: Test
        run: go test -json -v ./... 2>&1 | tee gotest.json

      - name: Test Report - Detailed
        uses: robherley/go-test-action@v1
        with:
          fromJSONFile: ./gotest.json
          omit: |
            untested
            stderr
            pie

      - name: Convert GoTest JSON to JUnit XML
        env:
          GO_JUNIT_REPORT_RELEASE: https://github.com/jstemmer/go-junit-report/releases/download/v2.1.0/go-junit-report-v2.1.0-linux-amd64.tar.gz
        shell: bash
        run: |
          # Download go-junit-report tools
          curl -L -s  ${GO_JUNIT_REPORT_RELEASE} | tar zxf - && chmod +x go-junit-report
          cat gotest.json | ./go-junit-report -parser gojson > gotest.xml

      - name: Test Report - Summary and Fail on Failure
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: gotest.xml
          commit: ${{github.event.workflow_run.head_sha}}
          require_tests: true
          fail_on_failure: true

          check_name: "Test Report - Summary"
          check_title_template: "{{CLASS_NAME}}:{{TEST_NAME}}"
          job_summary: true
          detailed_summary: false